services:
  - type: web
    name: x12-parser
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: -Xmx400m
