services:
  - type: web
    name: edi-format-converter
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: -Xmx400m --enable-native-access=ALL-UNNAMED
